/* ══════════════════════════════════════════════════════════════════════
   pdfKit — centralized PDF/document design system for EduNexa Analytics.

   Every downloadable/printable PDF in the app (receipts, report cards,
   class lists, fee reports, rankings, exam analysis, attendance, etc.)
   must be built using the pieces exported here rather than hand-rolled
   colors/margins/borders. That's what keeps every document — regardless
   of which page generates it — visually consistent, monochrome, and
   bordered, and it means a future style change happens in one place.

   Standard: black / white / grayscale only. No colored fills, text,
   badges, or charts in any generated document.
═══════════════════════════════════════════════════════════════════════ */
import jsPDF from 'jspdf';

/* ── Palette — the ONLY colors any PDF generator may use ────────────── */
export const PDF_COLORS = {
  black:     [0, 0, 0]       as [number, number, number],
  darkGray:  [60, 60, 60]    as [number, number, number],
  medGray:   [120, 120, 120] as [number, number, number],
  lightGray: [225, 225, 225] as [number, number, number],
  paleGray:  [245, 245, 245] as [number, number, number],
  white:     [255, 255, 255] as [number, number, number],
};

export const PDF_FONT = 'helvetica';

/* ── Page geometry ────────────────────────────────────────────────────
   PAGE_MARGIN: gap from the physical page edge to the border line.
   BORDER_INSET: gap from the border line to where content may start —
   this is what keeps tables/text/signatures/footers from ever touching
   or crossing the border itself. */
export const PDF_PAGE_MARGIN = 10;
export const PDF_BORDER_INSET = 5;
export const PDF_CONTENT_X = PDF_PAGE_MARGIN + PDF_BORDER_INSET;

/* ── Doc factory ──────────────────────────────────────────────────── */
export function createPdfDoc(orientation: 'p' | 'l' = 'p'): jsPDF {
  return new jsPDF(orientation, 'mm', 'a4');
}

/* ── Border — draws the enclosing rectangle on the CURRENT page ─────
   Call addBorderToAllPages() once, at the very end of a generator
   (after autoTable has finished adding any extra pages), rather than
   calling this per-page yourself. */
export function drawPageBorder(doc: jsPDF): void {
  const W = doc.internal.pageSize.width;
  const H = doc.internal.pageSize.height;
  doc.setDrawColor(...PDF_COLORS.black);
  doc.setLineWidth(0.6);
  doc.rect(
    PDF_PAGE_MARGIN, PDF_PAGE_MARGIN,
    W - PDF_PAGE_MARGIN * 2, H - PDF_PAGE_MARGIN * 2
  );
}

/** Adds a complete, consistent border to every page currently in the
 * document. Must run AFTER all content (including autoTable, which can
 * silently add its own pages) has been drawn. */
export function addBorderToAllPages(doc: jsPDF): void {
  const total = doc.internal.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    drawPageBorder(doc);
  }
}

/* ── Header — standard monochrome letterhead block ───────────────────
   Returns the Y position where table/body content should start, so
   callers pass that straight into autoTable's `startY`. */
export function drawPdfHeader(doc: jsPDF, opts: {
  schoolName: string;
  title: string;
  subtitle?: string;
  /** Extra left-aligned meta lines under the title, e.g. "CLASS: Grade 4",
   * "DATE: 13 August 2026" — rendered in the order given. */
  meta?: string[];
}): number {
  const W = doc.internal.pageSize.width;
  const x = PDF_CONTENT_X;
  const rightX = W - PDF_CONTENT_X;
  let y = PDF_PAGE_MARGIN + PDF_BORDER_INSET + 7;

  doc.setTextColor(...PDF_COLORS.black);
  doc.setFont(PDF_FONT, 'bold'); doc.setFontSize(15);
  doc.text(opts.schoolName.toUpperCase(), W / 2, y, { align: 'center' });
  y += 7;

  doc.setFont(PDF_FONT, 'bold'); doc.setFontSize(11);
  doc.text(opts.title.toUpperCase(), W / 2, y, { align: 'center' });
  y += 6;

  if (opts.subtitle) {
    doc.setFont(PDF_FONT, 'normal'); doc.setFontSize(9);
    doc.setTextColor(...PDF_COLORS.darkGray);
    doc.text(opts.subtitle, W / 2, y, { align: 'center' });
    y += 6;
  }

  doc.setDrawColor(...PDF_COLORS.black); doc.setLineWidth(0.3);
  doc.line(x, y, rightX, y);
  y += 5;

  if (opts.meta?.length) {
    doc.setFont(PDF_FONT, 'normal'); doc.setFontSize(8.5);
    doc.setTextColor(...PDF_COLORS.darkGray);
    opts.meta.forEach(line => { doc.text(line, x, y); y += 4.5; });
    y += 1;
  }

  doc.setTextColor(...PDF_COLORS.black);
  return y;
}

/* ── Footer — page numbers + generated-by line, on every page ───────── */
export function addPdfFooter(doc: jsPDF, generatedLabel = 'Generated by EduNexa Analytics'): void {
  const total = doc.internal.getNumberOfPages();
  const W = doc.internal.pageSize.width;
  const H = doc.internal.pageSize.height;
  const footerY = H - PDF_PAGE_MARGIN - PDF_BORDER_INSET + 3;
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setFont(PDF_FONT, 'normal'); doc.setFontSize(7.5);
    doc.setTextColor(...PDF_COLORS.medGray);
    doc.text(generatedLabel, PDF_CONTENT_X, footerY);
    doc.text(`Page ${i} of ${total}`, W - PDF_CONTENT_X, footerY, { align: 'right' });
  }
}

/** Finalizing helper — call once, last, right before doc.save()/output().
 * Adds the border to every page and the footer/page numbers in one go,
 * so generators can't forget one or the other or get the order wrong. */
export function finalizePdf(doc: jsPDF, generatedLabel?: string): void {
  addBorderToAllPages(doc);
  addPdfFooter(doc, generatedLabel);
}

/* ── Table theme — shared jspdf-autotable styling, grid/monochrome ──── */
export const PDF_TABLE_THEME = {
  theme: 'grid' as const,
  styles: {
    font: PDF_FONT,
    fontSize: 8.5,
    textColor: PDF_COLORS.black as unknown as number,
    lineColor: PDF_COLORS.black as unknown as number,
    lineWidth: 0.2,
    cellPadding: 2.2,
  },
  headStyles: {
    fillColor: PDF_COLORS.black as unknown as number,
    textColor: PDF_COLORS.white as unknown as number,
    fontStyle: 'bold' as const,
    halign: 'left' as const,
  },
  alternateRowStyles: {
    fillColor: PDF_COLORS.paleGray as unknown as number,
  },
  margin: { left: PDF_CONTENT_X, right: PDF_CONTENT_X },
};

/* ── Empty-state message — still produces a bordered, lettered doc ──── */
export function drawEmptyState(doc: jsPDF, message: string, startY: number): void {
  const W = doc.internal.pageSize.width;
  doc.setFont(PDF_FONT, 'italic'); doc.setFontSize(10);
  doc.setTextColor(...PDF_COLORS.darkGray);
  doc.text(message, W / 2, startY + 20, { align: 'center' });
  doc.setTextColor(...PDF_COLORS.black);
}

/* ── Summary/totals block — label-left, value-right pairs ───────────── */
export function drawSummaryBlock(doc: jsPDF, lines: [string, string][], startY: number): number {
  const W = doc.internal.pageSize.width;
  const x = PDF_CONTENT_X;
  const rightX = W - PDF_CONTENT_X;
  let y = startY;

  doc.setDrawColor(...PDF_COLORS.black); doc.setLineWidth(0.3);
  doc.line(x, y, rightX, y);
  y += 6;

  doc.setFont(PDF_FONT, 'bold'); doc.setFontSize(9.5);
  lines.forEach(([label, value]) => {
    doc.setTextColor(...PDF_COLORS.black);
    doc.text(label, x, y);
    doc.text(value, rightX, y, { align: 'right' });
    y += 6;
  });
  return y;
}
